### ISSUE TITLE
FR: ability to re-use the variables defined in the gradle project

### ISSUE THREAD

**Issue by evmin** [palantir/gradle-docker#108]
Would like to be able to reference gradle project variables. Something like that:
```
version: '2'
services:
  my-service:
    container_name: container
    image: "my/image:{{version}}"
```

Currently I get
```
> Failed to resolve Docker dependencies declared in project/docker-compose.yml.template: [{{version}}]. Known dependencies: {}
```
