### ISSUE TITLE
Better way to change base docker repo at command line time

### ISSUE THREAD

**Issue by tpetracca** [palantir/gradle-docker#141]
In my config I have something like
```
docker {
    name "docker.awesome.repository/${groupName}/${distName}:${project.version}"
    tags 'latest', 'snapshot'
    files tasks.distTar.outputs
}
```

on develop I would like to publish versioned docker images, but to a sandbox repository (like `sandbox.docker.awesome.repository`, not the main one.
Ideally I would do this without writing janky "is this a release build" code in gradle such as
```
def isRelease = ... // versioning logic here
def dockerRepoPrefix = (isRelease ? '' : 'sandbox.')
docker {
    name "${dockerRepoPrefix}docker.awesome.repository/${groupName}/${distName}:${project.version}"
    tags 'latest', 'snapshot'
    files tasks.distTar.outputs
}
```

Instead it would be cool in my `circle.yml` to do something like
```
deployment:
  develop:
    branch: develop
    owner: tomp
    commands:
      - ./gradlew -i dockerPushSnapshot dockerPush --repo='sandbox.docker.awesome.repository'
  release:
    tag: /[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?/
    owner: tomp
    commands:
      - ./gradlew -i dockerPushLatest dockerPush
```
