### ISSUE TITLE
New Feature: Allow multiple compose files

### ISSUE THREAD

**Issue by LionH** [palantir/gradle-docker#380]
## What happened?

I can see [here](https://github.com/palantir/gradle-docker/blob/develop/src/main/groovy/com/palantir/gradle/docker/DockerComposeUp.groovy#L49) that multiple compose files are not supported. It would be good that at least the DockerComposeUp task supports [this](https://docs.docker.com/compose/extends/)

## What did you want to happen?

In our case, we have a multi gradle project with common external dependencies we would like to extends on each module (like Mongo and Localstack).
Extending the common docker-compose-file with a templated docker-compose-override file would allow us to have those services defined in a single place.

## Possible solution:
I would allow DockerComposeUp task to accept extra docker compose files

**Comment by robert3005** [comment]
While DockerComposeUp only operates on single file that docker-compose file can reference other docker-compose files. It's a common pattern to define one global file with all the settings and many sub files that are specific compositions of services from that file.

docker-compose.yml
```
serviceA:
    extends:
      file: containers.yml
      service: serviceA
```

containers.yml
```
  serviceA:
    container_name: <container-name>
    image: <image>
    ...
```
