### ISSUE TITLE
Docker-compose plugin does not work with Gradle 6.4.1 - cannot resolve docker dependencies

### ISSUE THREAD

**Issue by Forinil** [palantir/gradle-docker#404]
## What happened?

I tried to use `com.palantir.docker-compose` with Gradle 6.4.1.

I created the project as follows

`settings.gradle.kts`:

```kotlin
rootProject.name = "project"
```

`build.gradle.kts`:

```kotlin
plugins {
    id("com.palantir.docker-compose") version "0.25.0"
}

repositories {
    jcenter()
}

dependencies {
    //Docker
    docker("library:rabbitmq:3.8.4")
}
```

`docker-compose.yml.template`

```yaml
version: '3'
services:
  rabbitmq:
    image: rabbitmq:{{library:rabbitmq}}
    environment:
      - TZ = Europe/Paris
      - RABBITMQ_DEFAULT_USER = user
      - RABBITMQ_DEFAULT_PASS = pass
    ports:
    - "55672:5672"
```

then ran:

`./gradlew generateDockerCompose`

and got result

> Task :generateDockerCompose FAILED

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':generateDockerCompose'.
> > Could not resolve all dependencies for configuration ':docker'.
>    > Could not find library:rabbitmq:3.8.4.
>      Searched in the following locations:
>        - https://jcenter.bintray.com/library/rabbitmq/3.8.4/rabbitmq-3.8.4.pom
>      If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to 
> adjust the 'metadataSources { ... }' of the repository declaration.
>      Required by:
>          project :

## What did you want to happen?

I wanted the following `docker-compose.yml` to be generated:

```yaml
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.4
    environment:
      - TZ = Europe/Paris
      - RABBITMQ_DEFAULT_USER = user
      - RABBITMQ_DEFAULT_PASS = pass
    ports:
    - "55672:5672"
```
